# Generated by Django 4.1 on 2023-02-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
