# Generated by Django 4.1 on 2023-02-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0002_remove_userinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.TextField(max_length=200)),
                ('text', models.TextField(max_length=200)),
                ('date', models.IntegerField(max_length=255)),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
