# Generated by Django 4.1 on 2023-02-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0003_postthread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostThread',
        ),
    ]
