# Generated by Django 4.1.6 on 2023-03-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0004_alter_commentthread_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentthread',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CS295P_Project.postthread'),
        ),
    ]
