# Generated by Django 3.2.18 on 2023-05-04 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CS295P_Project', '0005_alter_commentthread_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interact_id', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=32)),
                ('coins_history', models.IntegerField(default=0)),
                ('thread_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
