# Generated by Django 3.2.18 on 2023-05-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0006_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
    ]
