# Generated by Django 4.1 on 2023-02-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0007_postthread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostThread',
        ),
    ]
