# Generated by Django 3.2.18 on 2023-05-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0008_user_disliked_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='interact_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
