# Generated by Django 4.1 on 2023-02-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0008_delete_postthread'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('title', models.TextField(max_length=255)),
                ('content', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
