# Generated by Django 4.1.6 on 2023-05-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0009_alter_answerreward_date_alter_commentthread_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentthread',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postthread',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
