# Generated by Django 4.1.6 on 2023-05-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0010_alter_commentthread_date_alter_postthread_date'),
        ('CS295P_Project', '0010_alter_history_date'),
    ]

    operations = [
    ]
