# Generated by Django 4.1.6 on 2023-05-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0011_merge_20230509_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='postthread',
            name='taken_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
