# Generated by Django 4.1 on 2023-02-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0011_alter_postthread_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostThread',
        ),
    ]
