# Generated by Django 4.1.6 on 2023-05-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0013_history_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
