# Generated by Django 4.1 on 2023-02-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0014_postthread_unpdate_alter_postthread_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postthread',
            name='unpdate',
        ),
        migrations.AlterField(
            model_name='postthread',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
