# Generated by Django 4.1.6 on 2023-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0014_history_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='postthread',
            name='reward_id',
            field=models.IntegerField(default=0),
        ),
    ]
