# Generated by Django 4.1.6 on 2023-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0016_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
