# Generated by Django 4.1.6 on 2023-05-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0017_userprofile_unread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='unread_messages',
        ),
    ]
