# Generated by Django 4.1.6 on 2023-05-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0013_postthread_hided'),
        ('CS295P_Project', '0018_remove_userprofile_unread_messages'),
    ]

    operations = [
    ]
