# Generated by Django 4.1.6 on 2023-03-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0019_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
