# Generated by Django 4.1.6 on 2023-05-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS295P_Project', '0019_merge_20230518_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postthread',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
