# Generated by Django 4.1.6 on 2023-03-08 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CS295P_Project', '0021_rename_dislikes_postreward_watches_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookMark',
            new_name='BookMark_Reward',
        ),
        migrations.AlterField(
            model_name='bookmark_reward',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CS295P_Project.postreward'),
        ),
        migrations.CreateModel(
            name='BookMark_Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CS295P_Project.postthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
